#!/usr/bin/python

import binarydata
from modeldata import EventData
import os
import time


#~ def downsample(path):
    
	


if __name__ == "__main__":
    
    path = os.path.abspath('.') + "/"   
    print "refreshing data for:",path    
    
    foo = EventData(path)
    
    for dataset in ["cytosol.calcium", "er.calcium", "cytosol.stationary", "cytosol.dye", "cytosol.mobile", "cytosol.endogeneous"]:
	if os.path.exists(path + dataset + ".bin"):
	    binarydata.downsample(path,dataset)
        
    #for ip3 in ['0.01','0.02','0.035','0.045','0.05','0.06','0.07','0.08']:
    #	downsample('/datadisk/mrueckl/data/myocyte/6nm/single-cluster/mono/ip3='+ip3+'/')
        
    #downsample('/datadisk/mrueckl/data/myocyte/6nm/single-cluster/mono/normalip3/')
    #downsample('/datadisk/mrueckl/data/myocyte/6nm/single-cluster/mono/lowip3/')
    #downsample('/datadisk/mrueckl/data/myocyte/6nm/single-cluster/mono/ip3=0.035/')
    

    #downsample('/datadisk/mrueckl/data/myocyte/6nm/multi-cluster/mono/lowip3/')
    #downsample('/datadisk/mrueckl/data/myocyte/6nm/multi-cluster/mono/normalip3/')
    #downsample('/datadisk/mrueckl/data/myocyte/6nm/multi-cluster/mono/slowpumps/')
    
    






